(module
  (import "env" "g0" (global $g0 (mut i32)))
  (global $g1 (mut i32) (i32.const 42))
  (func (result i32)
    (global.get $g1)
    (i32.const 1)
    (i32.add)
    (global.set $g1)
    (global.get $g0)
    (i32.const 2)
    (i32.add)
    (global.set $g0)
    (global.get $g0)
  )
)
